// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nfc_smart_tag.proto

package com.appspot.nfcsmarttag.url;

public final class NfcSmartTag {
  private NfcSmartTag() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NfcSmartTagInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 number_serial_failure = 1;
    boolean hasNumberSerialFailure();
    int getNumberSerialFailure();
    
    // optional uint32 number_watchdog = 2;
    boolean hasNumberWatchdog();
    int getNumberWatchdog();
    
    // optional uint32 number_brown_out = 3;
    boolean hasNumberBrownOut();
    int getNumberBrownOut();
    
    // optional uint32 number_external_reset = 4;
    boolean hasNumberExternalReset();
    int getNumberExternalReset();
    
    // optional uint32 number_power_reset = 5;
    boolean hasNumberPowerReset();
    int getNumberPowerReset();
    
    // optional uint32 battery_voltage = 6;
    boolean hasBatteryVoltage();
    int getBatteryVoltage();
  }
  public static final class NfcSmartTagInfo extends
      com.google.protobuf.GeneratedMessage
      implements NfcSmartTagInfoOrBuilder {
    // Use NfcSmartTagInfo.newBuilder() to construct.
    private NfcSmartTagInfo(Builder builder) {
      super(builder);
    }
    private NfcSmartTagInfo(boolean noInit) {}
    
    private static final NfcSmartTagInfo defaultInstance;
    public static NfcSmartTagInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public NfcSmartTagInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NfcSmartTag.internal_static_NfcSmartTagInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NfcSmartTag.internal_static_NfcSmartTagInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 number_serial_failure = 1;
    public static final int NUMBER_SERIAL_FAILURE_FIELD_NUMBER = 1;
    private int numberSerialFailure_;
    public boolean hasNumberSerialFailure() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getNumberSerialFailure() {
      return numberSerialFailure_;
    }
    
    // optional uint32 number_watchdog = 2;
    public static final int NUMBER_WATCHDOG_FIELD_NUMBER = 2;
    private int numberWatchdog_;
    public boolean hasNumberWatchdog() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getNumberWatchdog() {
      return numberWatchdog_;
    }
    
    // optional uint32 number_brown_out = 3;
    public static final int NUMBER_BROWN_OUT_FIELD_NUMBER = 3;
    private int numberBrownOut_;
    public boolean hasNumberBrownOut() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNumberBrownOut() {
      return numberBrownOut_;
    }
    
    // optional uint32 number_external_reset = 4;
    public static final int NUMBER_EXTERNAL_RESET_FIELD_NUMBER = 4;
    private int numberExternalReset_;
    public boolean hasNumberExternalReset() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getNumberExternalReset() {
      return numberExternalReset_;
    }
    
    // optional uint32 number_power_reset = 5;
    public static final int NUMBER_POWER_RESET_FIELD_NUMBER = 5;
    private int numberPowerReset_;
    public boolean hasNumberPowerReset() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getNumberPowerReset() {
      return numberPowerReset_;
    }
    
    // optional uint32 battery_voltage = 6;
    public static final int BATTERY_VOLTAGE_FIELD_NUMBER = 6;
    private int batteryVoltage_;
    public boolean hasBatteryVoltage() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getBatteryVoltage() {
      return batteryVoltage_;
    }
    
    private void initFields() {
      numberSerialFailure_ = 0;
      numberWatchdog_ = 0;
      numberBrownOut_ = 0;
      numberExternalReset_ = 0;
      numberPowerReset_ = 0;
      batteryVoltage_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, numberSerialFailure_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, numberWatchdog_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, numberBrownOut_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, numberExternalReset_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, numberPowerReset_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, batteryVoltage_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, numberSerialFailure_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, numberWatchdog_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, numberBrownOut_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, numberExternalReset_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, numberPowerReset_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, batteryVoltage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static NfcSmartTag.NfcSmartTagInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static NfcSmartTag.NfcSmartTagInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static NfcSmartTag.NfcSmartTagInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static NfcSmartTag.NfcSmartTagInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static NfcSmartTag.NfcSmartTagInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static NfcSmartTag.NfcSmartTagInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static NfcSmartTag.NfcSmartTagInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static NfcSmartTag.NfcSmartTagInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static NfcSmartTag.NfcSmartTagInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static NfcSmartTag.NfcSmartTagInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NfcSmartTag.NfcSmartTagInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NfcSmartTag.NfcSmartTagInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NfcSmartTag.internal_static_NfcSmartTagInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NfcSmartTag.internal_static_NfcSmartTagInfo_fieldAccessorTable;
      }
      
      // Construct using NfcSmartTag.NfcSmartTagInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        numberSerialFailure_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        numberWatchdog_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        numberBrownOut_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        numberExternalReset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        numberPowerReset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        batteryVoltage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NfcSmartTag.NfcSmartTagInfo.getDescriptor();
      }
      
      public NfcSmartTag.NfcSmartTagInfo getDefaultInstanceForType() {
        return NfcSmartTag.NfcSmartTagInfo.getDefaultInstance();
      }
      
      public NfcSmartTag.NfcSmartTagInfo build() {
        NfcSmartTag.NfcSmartTagInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private NfcSmartTag.NfcSmartTagInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        NfcSmartTag.NfcSmartTagInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public NfcSmartTag.NfcSmartTagInfo buildPartial() {
        NfcSmartTag.NfcSmartTagInfo result = new NfcSmartTag.NfcSmartTagInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.numberSerialFailure_ = numberSerialFailure_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.numberWatchdog_ = numberWatchdog_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.numberBrownOut_ = numberBrownOut_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.numberExternalReset_ = numberExternalReset_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.numberPowerReset_ = numberPowerReset_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.batteryVoltage_ = batteryVoltage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NfcSmartTag.NfcSmartTagInfo) {
          return mergeFrom((NfcSmartTag.NfcSmartTagInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(NfcSmartTag.NfcSmartTagInfo other) {
        if (other == NfcSmartTag.NfcSmartTagInfo.getDefaultInstance()) return this;
        if (other.hasNumberSerialFailure()) {
          setNumberSerialFailure(other.getNumberSerialFailure());
        }
        if (other.hasNumberWatchdog()) {
          setNumberWatchdog(other.getNumberWatchdog());
        }
        if (other.hasNumberBrownOut()) {
          setNumberBrownOut(other.getNumberBrownOut());
        }
        if (other.hasNumberExternalReset()) {
          setNumberExternalReset(other.getNumberExternalReset());
        }
        if (other.hasNumberPowerReset()) {
          setNumberPowerReset(other.getNumberPowerReset());
        }
        if (other.hasBatteryVoltage()) {
          setBatteryVoltage(other.getBatteryVoltage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              numberSerialFailure_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              numberWatchdog_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              numberBrownOut_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              numberExternalReset_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              numberPowerReset_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              batteryVoltage_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 number_serial_failure = 1;
      private int numberSerialFailure_ ;
      public boolean hasNumberSerialFailure() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getNumberSerialFailure() {
        return numberSerialFailure_;
      }
      public Builder setNumberSerialFailure(int value) {
        bitField0_ |= 0x00000001;
        numberSerialFailure_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumberSerialFailure() {
        bitField0_ = (bitField0_ & ~0x00000001);
        numberSerialFailure_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 number_watchdog = 2;
      private int numberWatchdog_ ;
      public boolean hasNumberWatchdog() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getNumberWatchdog() {
        return numberWatchdog_;
      }
      public Builder setNumberWatchdog(int value) {
        bitField0_ |= 0x00000002;
        numberWatchdog_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumberWatchdog() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numberWatchdog_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 number_brown_out = 3;
      private int numberBrownOut_ ;
      public boolean hasNumberBrownOut() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNumberBrownOut() {
        return numberBrownOut_;
      }
      public Builder setNumberBrownOut(int value) {
        bitField0_ |= 0x00000004;
        numberBrownOut_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumberBrownOut() {
        bitField0_ = (bitField0_ & ~0x00000004);
        numberBrownOut_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 number_external_reset = 4;
      private int numberExternalReset_ ;
      public boolean hasNumberExternalReset() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getNumberExternalReset() {
        return numberExternalReset_;
      }
      public Builder setNumberExternalReset(int value) {
        bitField0_ |= 0x00000008;
        numberExternalReset_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumberExternalReset() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numberExternalReset_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 number_power_reset = 5;
      private int numberPowerReset_ ;
      public boolean hasNumberPowerReset() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getNumberPowerReset() {
        return numberPowerReset_;
      }
      public Builder setNumberPowerReset(int value) {
        bitField0_ |= 0x00000010;
        numberPowerReset_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumberPowerReset() {
        bitField0_ = (bitField0_ & ~0x00000010);
        numberPowerReset_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 battery_voltage = 6;
      private int batteryVoltage_ ;
      public boolean hasBatteryVoltage() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getBatteryVoltage() {
        return batteryVoltage_;
      }
      public Builder setBatteryVoltage(int value) {
        bitField0_ |= 0x00000020;
        batteryVoltage_ = value;
        onChanged();
        return this;
      }
      public Builder clearBatteryVoltage() {
        bitField0_ = (bitField0_ & ~0x00000020);
        batteryVoltage_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:NfcSmartTagInfo)
    }
    
    static {
      defaultInstance = new NfcSmartTagInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NfcSmartTagInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NfcSmartTagInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NfcSmartTagInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023nfc_smart_tag.proto\"\267\001\n\017NfcSmartTagInf" +
      "o\022\035\n\025number_serial_failure\030\001 \001(\r\022\027\n\017numb" +
      "er_watchdog\030\002 \001(\r\022\030\n\020number_brown_out\030\003 " +
      "\001(\r\022\035\n\025number_external_reset\030\004 \001(\r\022\032\n\022nu" +
      "mber_power_reset\030\005 \001(\r\022\027\n\017battery_voltag" +
      "e\030\006 \001(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NfcSmartTagInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NfcSmartTagInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NfcSmartTagInfo_descriptor,
              new java.lang.String[] { "NumberSerialFailure", "NumberWatchdog", "NumberBrownOut", "NumberExternalReset", "NumberPowerReset", "BatteryVoltage", },
              NfcSmartTag.NfcSmartTagInfo.class,
              NfcSmartTag.NfcSmartTagInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
