/* Generated by the program. DO NOT EDIT! */
#include "base_station.pb.h"
static inline bool is_full(uint8_t *bufp, uint8_t *end)
{
  return (bufp > end);
}

static void uint32_to_proto(uint8_t **bufp, uint8_t *end, uint32_t value)
{
  if (is_full(*bufp, end))
    return;

  while (value > 0x7F && !is_full(*bufp, end)) {
    **bufp = ((uint8_t)(value) & 0x7F) | 0x80;
    (*bufp)++;
    value >>= 7;
  }

  if (!is_full(*bufp, end)) {
    **bufp = (uint8_t)(value) & 0x7F;
    (*bufp)++;
  }
}

static bool uint32_to_proto_helper(uint8_t **buf, uint8_t *end,
                                   uint32_t field, uint32_t value)
{
  uint8_t *bufp = *buf;

  uint32_to_proto(&bufp, end, field << 3 | 0);
  uint32_to_proto(&bufp, end, value);

  if (is_full(bufp, end)) {
    return false;
  } else {
    *buf = bufp;
    return true;
  }
}


bool serialize_NfcBaseStationInfo__battery_voltage(uint8_t **buf, uint8_t *end, uint32_t value)
{
  return uint32_to_proto_helper(buf, end, 6, value);
}

bool serialize_NfcBaseStationInfo__number_power_reset(uint8_t **buf, uint8_t *end, uint32_t value)
{
  return uint32_to_proto_helper(buf, end, 5, value);
}

bool serialize_NfcBaseStationInfo__number_serial_failure(uint8_t **buf, uint8_t *end, uint32_t value)
{
  return uint32_to_proto_helper(buf, end, 1, value);
}

bool serialize_NfcBaseStationInfo__number_watchdog(uint8_t **buf, uint8_t *end, uint32_t value)
{
  return uint32_to_proto_helper(buf, end, 2, value);
}

bool serialize_NfcBaseStationInfo__number_external_reset(uint8_t **buf, uint8_t *end, uint32_t value)
{
  return uint32_to_proto_helper(buf, end, 4, value);
}

bool serialize_NfcBaseStationInfo__number_brown_out(uint8_t **buf, uint8_t *end, uint32_t value)
{
  return uint32_to_proto_helper(buf, end, 3, value);
}

