/* Generated by the program. DO NOT EDIT! */

#include <stdint.h>
#include <stdbool.h>
bool serialize_NfcBaseStationInfo__battery_voltage(uint8_t **buf, uint8_t *end, uint32_t value);
bool serialize_NfcBaseStationInfo__number_power_reset(uint8_t **buf, uint8_t *end, uint32_t value);
bool serialize_NfcBaseStationInfo__number_serial_failure(uint8_t **buf, uint8_t *end, uint32_t value);
bool serialize_NfcBaseStationInfo__number_watchdog(uint8_t **buf, uint8_t *end, uint32_t value);
bool serialize_NfcBaseStationInfo__number_external_reset(uint8_t **buf, uint8_t *end, uint32_t value);
bool serialize_NfcBaseStationInfo__number_brown_out(uint8_t **buf, uint8_t *end, uint32_t value);
